- éthiopienne
- sénégalaise
- marocaine
- libanaise
- iranienne
- géorgienne
- turque
- ouzbèke
- indienne du Sud
- sri-lankaise
- népalaise
- tibétaine
- sichuanaise
- cantonaise
- taïwanaise
- coréenne
- japonaise familiale
- vietnamienne
- thaïlandaise
- indonésienne
- philippine
- mexicaine
- péruvienne
- colombienne
- brésilienne
- argentine
- jamaïcaine
- haïtienne
- grecque
- italienne régionale
- espagnole (tapas)
- portugaise
- polonaise
- scandinave
- belge revisitée
- nord-africaine végétarienne
- ouest-africaine
- israélienne
- syrienne
- afghane
