- gqom (Durban)
- amapiano des débuts
- kuduro
- baile funk / funk carioca
- cumbia villera
- cumbia psicodélica / chicha
- zouglou
- coupé-décalé
- highlife ghanéen des années 70
- afrobeat nigérian originel
- Ethio-jazz
- tuareg desert blues
- mbalax
- shangaan electro
- singeli (Tanzanie)
- chaabi algérois
- raï des années 80
- mahraganat (Égypte)
- dabke électronique
- arabesk turc
- anadolu rock
- rebetiko
- manele
- turbo-folk
- sevdah
- joik sami
- tuvan throat singing / khoomei
- dangdut koplo
- gamelan expérimental
- enka
- city pop
- shibuya-kei
- japanoise
- trot coréen
- bhangra britannique
- Asian Underground (Londres)
- qawwali
- baul
- Carnatic fusion
- baila (Sri Lanka)
- kwaito
- gnawa
- sega mauricien et maloya réunionnais
- zouk béton / zouk love
- bouyon (Dominique)
- dancehall digital des années 80
- dub poetry
- calypso et soca
- son jarocho
- norteño et corridos tumbados
- huayno
- chamamé
- forró
- tropicália
- mangue beat
- footwork (Chicago)
- Jersey club
- Baltimore club
- ghetto house
- Detroit electro
- Miami bass
- chopped and screwed
- Memphis rap underground
- horrorcore
- drill UK
- grime
- UK funky
- dubstep des origines (Croydon)
- jungle ragga
- liquid drum and bass
- neurofunk
- halftime
- breakcore
- speedcore
- gabber
- hardtek / free party
- new beat belge
- EBM
- minimal wave
- coldwave
- darkwave
- post-punk soviétique
- no wave
- krautrock
- zeuhl
- math rock
- shoegaze
- slowcore
- screamo / emoviolence
- crust punk
- D-beat
- riot grrrl
- anarcho-punk
- surf rock
- garage rock des sixties
- psych rock thaï (luk thung psyché)
- ambient japonais (kankyō ongaku)
- vaporwave
- hyperpop
- witch house
- lo-fi house
- deconstructed club
- dembow
- reggaeton old school
- baile de favela eletrônico
- trip-hop bristolien
- illbient
- glitch
