- rave britannique de 1988-92 (acid house)
- free party et teufeurs
- gabbers néerlandais
- new beat et clubs belges
- punks de 1977
- anarcho-punk et crust
- skinheads traditionnels (origine jamaïcaine, anti-racistes)
- mods
- rude boys et 2 Tone
- goths et batcave
- cybergoths
- rivetheads / scène EBM
- straight edge hardcore
- riot grrrl
- grunge
- skaters des années 90
- b-boys et culture breakdance
- tekno et sound systems nomades
- psytrance et goa
- darkwear et techwear
- scène ballroom et voguing
- sapeurs congolais (la Sape)
- visual kei
- gyaru
- bōsōzoku
- cholos et lowriders
- rockabilly et psychobilly
- casuals et culture foot anglaise
- métalleux et battle jackets
- scène drill et UK road
- emo des années 2000
- scène queer punk (queercore)
- hippies psychédéliques et freaks
- zazous
- teddy boys
- cottagecore et néo-ruralité
- scène vaporwave / seapunk
- gorpcore
- scène kawaii / decora
- blokecore
